'use client';

import './globals.css'
import { SessionProvider } from "next-auth/react";
import Navbar from '@/components/commons/Navbar';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children, session
}: {
  children: React.ReactNode
  session: any
}) {

  return (
    <html lang="en">
      <SessionProvider session={session}>
        <body>
          <Navbar/>
          {children}
        </body>
      </SessionProvider>
    </html>
  )
}

// "11577aec-2bc5-47ca-bf15-bf94d530d3d1"